version: '2.3'
services:
  frontend:
    container_name: frontend
    image: nginx:alpine
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html
    networks:
      - phonebook_network

  backend:
    container_name: backend
    image: jetty:9.4.31-jre8
    ports:
      - "127.0.0.1:8090:8080"
    volumes:
      - ./backend/target/backend.war:/var/lib/jetty/webapps/backend.war
      - ./frontend/target/frontend.war:/var/lib/jetty/webapps/frontend.war
    networks:
      - phonebook_network
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: mysql
    image: mysql:5.7
    networks:
      - phonebook_network
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: phonebook-user
      MYSQL_PASSWORD: phonebook-password
      MYSQL_DATABASE: phonebook
      MYSQL_ROOT_HOST: "%"
    healthcheck:
      test: "mysql -u root -p${MYSQL_ROOT_PASSWORD} -e 'select 1'"
      interval: 5s
      retries: 10

networks:
  phonebook_network: