version: '3.8'
services:
  jetty:
    container_name: jetty
    image: jetty:9.4.31-jre8
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./target/phonebook.war:/var/lib/jetty/webapps/phonebook.war
    networks:
      - backend
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:5.7
    networks:
      - backend
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: phonebook-user
      MYSQL_PASSWORD: phonebook-password
      MYSQL_DATABASE: phonebook
      MYSQL_ROOT_HOST: "%"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER

networks:
  backend: