version: '2.3'
services:
  jetty:
    container_name: jetty
    image: jetty:9.4.31-jre8
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./backend/target/backend.war:/var/lib/jetty/webapps/backend.war
    networks:
      - backend
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: mysql
    image: mysql:5.7
    networks:
      - backend
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: phonebook-user
      MYSQL_PASSWORD: phonebook-password
      MYSQL_DATABASE: phonebook
      MYSQL_ROOT_HOST: "%"
    healthcheck:
      test: "mysql -u root -p${MYSQL_ROOT_PASSWORD} -e 'select 1'"
      interval: 5s
      retries: 10

networks:
  backend: